spring:
    datasource:
        url: jdbc:postgresql://203.228.54.37:15432/medicine  # DB ?? URL
        username: indie  # DB 사용자명
        password: "indie7942"  # DB 비밀번호
        driver-class-name: org.postgresql.Driver  # PostgreSQL JDBC 드라이버
        hikari:
            maximum-pool-size: 3  # HikariCP 커넥션 풀 크기
            minimum-idle: 1  # 최소 IDLE 커넥션 수
#            connection-timeout: 30000  # 커넥션 타임아웃 (30초)
#            idle-timeout: 600000  # 아이들 타임아웃 (10분)
#            max-lifetime: 1800000  # 커넥션 최대 수명 (30분)

    jwt:
        expiration:
            access: 86400000  # Access Token 만료 시간 (1일)
            refresh: 2592000000 # Access Token 만료 시간 (30일)
        key: temp # JWT 서명 키

    jpa:
        hibernate:
            ddl-auto: update  # 개발 환경에서만 'update'로 설정, 운영 환경에서는 'none' 또는 'validate'로 설정
        show-sql: true  # SQL 쿼리 출력 여부
        properties:
            hibernate:
                format_sql: true  # SQL 포맷팅 여부
#                dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate Dialect 설정
        database: postgresql # 데이터베이스 종류

    server:
        port: 8080  # 서버 포트 설정

    logging:
        level:
            org.springframework.web: DEBUG  # HTTP 요청/응답 로그 레벨 설정

    data:
        redis:
            host: localhost
            port: 6379
            password: "Egis2395!@"

# SpringDoc OpenAPI 설정
springdoc:
    api-docs:
        enabled: true # API 문서화 활성화
        path: /v3/api-docs  # Swagger JSON 엔드포인트 (기본값 그대로 써도 무방)
    swagger-ui:
        enabled: true # Swagger UI 활성화
        path: /swagger-ui.html  # UI 접속 경로
        display-request-duration: true  # 요청 시간 표시
        doc-expansion: list  # 'none', 'list', 'full' 중 선택 (none이면 기본으로 닫힘)
        try-it-out-enabled: true  # 기본으로 Try It Out 활성화
        filter: false  # 검색창 활성화
        operations-sorter: alpha  # 메서드 알파벳 순 정렬
        tags-sorter: alpha  # 태그 정렬
    default-produces-media-type: application/json # 기본 응답 미디어 타입
    default-consumes-media-type: application/json # 기본 요청 미디어 타입
